stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
    - dev
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        DOMAIN="assistant.greatmachineinthesky.com"
      elif [ "$CI_COMMIT_REF_NAME" = "dev" ]; then
        DOMAIN="assistant-dev.greatmachineinthesky.com"
      fi
    - |
      curl -X POST \
        -H "Authorization: token $DOCKER_SERVER_ACTIONS_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/json" \
        https://api.github.com/repos/adamd9/docker-server/dispatches \
        -d "{\"event_type\": \"deploy-service\", \"client_payload\": {\"domain\": \"$DOMAIN\", \"action\": \"down-up\"}}"
  variables:
    # Define any additional variables needed here
    # The DOCKER_SERVER_ACTIONS_TOKEN should be set in GitLab CI/CD Variables settings
