version: '3'  
services:  
  llm-agent:  
    build: .  
    volumes:  
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
      - ./data:/usr/src/app/data  # Mount r2o1 as data directory
    ports:  
      - "3000:3000"
    environment:
      - NODE_ENV=development
