name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set domain based on branch
        id: set-domain
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DOMAIN=assistant.greatmachineinthesky.com" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "DOMAIN=assistant-dev.greatmachineinthesky.com" >> $GITHUB_ENV
          fi
          
      - name: Trigger Docker Server Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCKER_SERVER_ACTIONS_TOKEN }}
          repository: adamd9/docker-server
          event-type: deploy-service
          client-payload: '{"domain": "${{ env.DOMAIN }}", "action": "down-up"}'
